Update deploy_to_ecs

diff --git a/deploy_to_ecs b/deploy_to_ecs
--- a/deploy_to_ecs
+++ b/deploy_to_ecs
@@ -67,7 +67,7 @@ SUCCESS=false
 
 for i in {1..10}
 do
-	ecs-cli compose --debug -p "$SERVICE_NAME" -f $COMPOSE_FILE service up && $SUCCESS=true && break || echo "service up failed. Will retry after 10 seconds..." && sleep 10;
+	ecs-cli compose --debug -p "$SERVICE_NAME" -f $COMPOSE_FILE service up && export SUCCESS=true && break || echo "service up failed. Will retry after 10 seconds..." && sleep 10;
 done
 
 if [ "$SUCCESS" = true ] ; then
